# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BenchmarkFcns
author: 'Mazhar Ansari Ardeh'
email: mazhar.ansari.ardeh[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Benchmarkfcns is a personal effort to provide a public repository of sources 
  and documents for well-known optimization benchmark functions.
  Please visit the About page for more information. 
#baseurl: "" # the subpath of your site, e.g. /blog
url: "benchmarkfcns.info" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  mazhar-ansari-ardeh

# Build settings
markdown: kramdown

category-list: [optimization]

plugins: [jekyll-seo-tag]
